Update execution.py for flexible conformance handling.
A validation generator function has been aded along with the ability to specify custom functions for validating individual types.

cli args have been added in the form of 

--type-conformance='arg'

with the following args: 
all : attempts to convert any mistyped inputs/outputs to the type specified by the node

images : only enforces BHW3 on images, doing the minimum verifiably accurate transforms such as MASK HW and BHW to BHW3

error: raises an error with information about the type mismatch at the node where it occurs.

none: the default value, it outputs errors to console, and does nothing else. 

This should address most of the areas of discussion.